language: dart
sudo: false
dart:
  - dev
  - stable
  - 1.22.1
  - 1.21.1
  - 1.20.1
  - 1.19.1
cache:
  directories:
    - $HOME/.pub-cache
dart_task:
  - test: --platform vm
  - dartfmt
  - dartanalyzer
