name: shelf_static
version: 0.2.7
author: Dart Team <misc@dartlang.org>
description: Static file server support for Shelf
homepage: https://github.com/dart-lang/shelf_static
environment:
  sdk: '>=1.24.0 <2.0.0'
dependencies:
  convert: '>=1.0.0 <3.0.0'
  http_parser: '>=0.0.2+2 <4.0.0'
  mime: '>=0.9.0 <0.10.0'
  path: '>=1.1.0 <2.0.0'
  shelf: '>=0.5.7 <0.8.0'
dev_dependencies:
  args: '^1.0.0'
  test: '>=0.12.0 <0.13.0'
  test_descriptor: '^1.0.0'

